In [1]:
import joblib
import pandas as pd
#load your model for further usage
gs = joblib.load("tree.pkl")

In [23]:
gs.best_params_["classifier"]

DecisionTreeClassifier(ccp_alpha=0.001, criterion='entropy', max_depth=40,
                       max_leaf_nodes=200, min_impurity_decrease=0,
                       min_samples_leaf=5, random_state=42)

In [2]:
results = pd.DataFrame(gs.cv_results_)

In [3]:
results.sort_values('rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
756       1.454513      0.048367         0.005291        0.000831   
752       1.497945      0.041620         0.005171        0.000901   
754       1.452940      0.033484         0.004753        0.001112   
758       1.455573      0.065135         0.005056        0.001381   
760       1.537621      0.041070         0.005819        0.001846   
..             ...           ...              ...             ...   
949       0.903617      0.044336         0.004765        0.000818   
951       0.870871      0.056844         0.006024        0.002062   
953       0.871608      0.051862         0.004826        0.001421   
933       0.849255      0.078591         0.004323        0.000663   
999       1.040305      0.041990         0.006101        0.003014   

                                      param_classifier  \
756  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
752  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
754  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
758  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
760  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
..                                                 ...   
949  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
951  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
953  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
933  DecisionTreeClassifier(ccp_alpha=0.001, criter...   
999  DecisionTreeClassifier(ccp_alpha=0.001, criter...   

    param_classifier__ccp_alpha param_classifier__criterion  \
756                       0.001                     entropy   
752                       0.001                     entropy   
754                       0.001                     entropy   
758                       0.001                     entropy   
760                       0.001                     entropy   
..                          ...                         ...   
949                        0.01                        gini   
951                        0.01                        gini   
953                        0.01                        gini   
933                        0.01                        gini   
999                        0.01                        gini   

    param_classifier__max_depth param_classifier__max_leaf_nodes  \
756                          40                              200   
752                          40                              200   
754                          40                              200   
758                          40                              200   
760                          40                              200   
..                          ...                              ...   
949                          10                              200   
951                          10                              200   
953                          10                              200   
933                          10                              100   
999                          15                              100   

    param_classifier__min_impurity_decrease  ... split3_test_score  \
756                                       0  ...          0.973710   
752                                       0  ...          0.973710   
754                                       0  ...          0.973710   
758                                       0  ...          0.973710   
760                                       0  ...          0.970524   
..                                      ...  ...               ...   
949                                       0  ...          0.657240   
951                                       0  ...          0.657240   
953                                       0  ...          0.657240   
933                                       0  ...          0.657240   
999                                       0  ...          0.657240   

    split4_test_score split5_test_score split6_test_score  split

In [4]:
sorted_results = results.sort_values('rank_test_score')

In [5]:
import numpy as np
from sklearn.metrics import *
with open('data.npy', 'rb') as f:
    train_data = np.load(f)
    test_data = np.load(f)
    train_label = np.load(f)
    test_label = np.load(f)

In [6]:
sorted_results.iloc[100]

mean_fit_time                                                                       0.921317
std_fit_time                                                                        0.058035
mean_score_time                                                                     0.005655
std_score_time                                                                      0.001972
param_classifier                           DecisionTreeClassifier(ccp_alpha=0.001, criter...
param_classifier__ccp_alpha                                                            0.001
param_classifier__criterion                                                             gini
param_classifier__max_depth                                                               20
param_classifier__max_leaf_nodes                                                         200
param_classifier__min_impurity_decrease                                                    0
param_classifier__min_samples_leaf                                    

In [22]:
# e.g. Accuracy, Precision etc.
# PERFORMANCE ON TRAINING DATASET
#best_clf = a.best_params_["classifier"]
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import *

b_result = sorted_results.iloc[0]
best_clf = DecisionTreeClassifier(ccp_alpha = b_result["param_classifier__ccp_alpha"],
                                  criterion = b_result["param_classifier__criterion"],
                                  max_depth = b_result["param_classifier__max_depth"],
                                  max_leaf_nodes = b_result["param_classifier__max_leaf_nodes"],
                                  min_impurity_decrease = b_result["param_classifier__ccp_alpha"],
                                  min_samples_leaf = b_result["param_classifier__min_samples_leaf"],
                                  min_samples_split = b_result["param_classifier__min_samples_split"],
                                  splitter = b_result["param_classifier__splitter"])
best_clf.fit(train_data,train_label)
prediction = best_clf.predict(train_data)

accuracy_tf = accuracy_score(train_label,prediction)
precision_tf = precision_score(train_label,prediction)
recall_tf = recall_score(train_label,prediction)
f1_tf = f1_score(train_label,prediction)
confusion_matrix_tf = confusion_matrix(train_label, prediction)

print("Accuracy with transformed data: ",accuracy_tf)
print("Precision with transformed data: ",precision_tf)
print("Recall with transformed data: ",recall_tf)
print("F1 score with transformed data: ",f1_tf)

print(confusion_matrix_tf)
prediction = best_clf.predict(test_data)

accuracy_tf = accuracy_score(test_label,prediction)
precision_tf = precision_score(test_label,prediction)
recall_tf = recall_score(test_label,prediction)
f1_tf = f1_score(test_label,prediction)
confusion_matrix_tf = confusion_matrix(test_label, prediction)

print("Accuracy with transformed data: ",accuracy_tf)
print("Precision with transformed data: ",precision_tf)
print("Recall with transformed data: ",recall_tf)
print("F1 score with transformed data: ",f1_tf)
print(confusion_matrix_tf)


Accuracy with transformed data:  0.9749865572660467
Precision with transformed data:  0.9700538839349578
Recall with transformed data:  0.9700538839349578
F1 score with transformed data:  0.9700538839349578
[[28614   628]
 [  628 20343]]
Accuracy with transformed data:  0.5710206337509212
Precision with transformed data:  0.7478455154803703
Recall with transformed data:  0.37729468599033816
F1 score with transformed data:  0.5015519640372472
[[3856  790]
 [3867 2343]]


In [21]:
best_clf

DecisionTreeClassifier(ccp_alpha=0.01, max_depth=15, max_leaf_nodes=100,
                       min_impurity_decrease=0.01, min_samples_leaf=5,
                       min_samples_split=10, splitter='random')

In [16]:
# PERFORMANCE ON TEST DATASET


Accuracy with transformed data:  0.5007369196757553
Precision with transformed data:  0.6478293413173652
Recall with transformed data:  0.278743961352657
F1 score with transformed data:  0.389777077234857
[[3705  941]
 [4479 1731]]
